In [18]:
import pandas as pd
import numpy as np
import MySQLdb

In [19]:
Anio='2018'
Mes='09'
Dia_act='10'

In [20]:
#nombre de los archivos Asignacion normal
nom_actual_cor='..\..\..\..\BASES DATATOOLS\ASIGNACION\\2018\\SEPTIEMBRE\Sistema de cobro_'+Dia_act+'_'+Mes+'_'+Anio+'.xlsx'
nombre_hoja_cor='Asignacion'
cartera_cor='CORRIENTE'

# nombre de los archivos Menores
nom_actual_men='..\..\..\..\BASES DATATOOLS\ASIGNACION\\2018\\SEPTIEMBRE\Sistema de cobro_'+Dia_act+'_'+Mes+'_'+Anio+'.xlsx'
nombre_hoja_men='Menores'
cartera_men='MENORES'

In [21]:
def agregar_ceros(num):
    ced=num['IDENTIFICACION_DEUDOR']
    if len(ced)==9 or len(ced)==12 :
        if ced.isdigit():
            return '0'+ced
    return ced

In [22]:
#leer archivo excel asignacion actual y anterior
asignacion_actual_cor=pd.read_excel(open(nom_actual_cor,'rb'), sheet_name=nombre_hoja_cor, dtype={"IDENTIFICACION_DEUDOR": str})
#leer archivo excel asignacion actual y anterior
asignacion_actual_men=pd.read_excel(open(nom_actual_men,'rb'), sheet_name=nombre_hoja_men, dtype={"IDENTIFICACION_DEUDOR": str})

In [24]:
asignacion_actual_cor.columns

Index(['IDENTIFICACION_DEUDOR', 'TIPO_IDENTIFICACION', 'NUMERO_CUENTA',
       'ESTADO AXIS', 'ESTADO_CREDITO', 'SALDO', 'DIAS_MORA', 'ESTADO',
       'CODIGO_CONDICION', 'PLACA_VEHICULO', 'DESCRIPCION_INFRACION',
       'FECHA_PRESCRIBE', 'FECHA_ULTIMA_GESTION', 'RAZONSOCIAL',
       'PRIMER_APELLIDO', 'SEGUNDO_APELLIDO', 'PRIMER_NOMBRE',
       'SEGUNDO_NOMBRE', 'CAMPANAPORCLIENTE', 'SUBCAMPANAPORCLIENTE',
       'USUARIOPORCLIENTE', 'CASACOBRANZAPORCLIENTE', 'FECHA_ULTIMA_FACT',
       'MEJOR_RESPUESTA', 'FECHA_COACTIVA'],
      dtype='object')

In [36]:
asignacion_actual_cor= asignacion_actual_cor.fillna('')
asignacion_actual_cor['ID']=asignacion_actual_cor.apply(agregar_ceros,axis=1)
asignacion_actual_cor['SUBCAMPANAPORCLIENTE'].replace(to_replace=[''],value='4. VENCIDA FASE I',inplace=True)
asignacion_actual_cor['FECHA_COACTIVA'].replace(to_replace=[''],value='NO COACTIVA',inplace=True)
asignacion_actual_cor['NOMBRE']=asignacion_actual_cor['RAZONSOCIAL']+' '+asignacion_actual_cor['PRIMER_APELLIDO']+' '+asignacion_actual_cor['SEGUNDO_APELLIDO']+' '+asignacion_actual_cor['PRIMER_NOMBRE']
asignacion_actual_cor['CARTERA']='CORRIENTE'
base_gestion_cor=asignacion_actual_cor[['IDENTIFICACION_DEUDOR','ID','NOMBRE','SALDO','FECHA_COACTIVA','SUBCAMPANAPORCLIENTE','DIAS_MORA','CARTERA']]
# ordenada_cor=base_gestion_cor.groupby(['IDENTIFICACION_DEUDOR','ID','NOMBRE','SUBCAMPANAPORCLIENTE','FECHA_COACTIVA']).sum()
ordenada_cor=base_gestion_cor.groupby(['IDENTIFICACION_DEUDOR','ID','NOMBRE','SUBCAMPANAPORCLIENTE','FECHA_COACTIVA','CARTERA']).agg({'SALDO':'sum','DIAS_MORA':['min', 'max']})

In [37]:
ordenada_cor.head()

                                                                                                          SALDO  \
                                                                                                            sum
IDENTIFICACION_DEUDOR ID         NOMBRE                    SUBCAMPANAPORCLIENTE FECHA_COACTIVA CARTERA
1000559797            1000559797  RECALDE ESPINOSA ALFONSO 5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  131.8
1000723724            1000723724  GARZON ECHEVERRIA JUAN   3.5 VENCIDA 0-30     NO COACTIVA    CORRIENTE  115.8
1000793024            1000793024  RODRIGUEZ MURIEL NOE     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  109.8
1001145398            1001145398  CIFUENTES REINA JOSE     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  483.0
1001213899            1001213899  DE JESUS BORJA OSCAR     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  308.8

                                                                                                         DIAS_MORA  \
                                                                                                               min
IDENTIFICACION_DEUDOR ID         NOMBRE                    SUBCAMPANAPORCLIENTE FECHA_COACTIVA CARTERA
1000559797            1000559797  RECALDE ESPINOSA ALFONSO 5. VENCIDA FASE II   NO COACTIVA    CORRIENTE        21
1000723724            1000723724  GARZON ECHEVERRIA JUAN   3.5 VENCIDA 0-30     NO COACTIVA    CORRIENTE        21
1000793024            1000793024  RODRIGUEZ MURIEL NOE     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE       661
1001145398            1001145398  CIFUENTES REINA JOSE     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE       484
1001213899            1001213899  DE JESUS BORJA OSCAR     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE       416


                                                                                                          max
IDENTIFICACION_DEUDOR ID         NOMBRE                    SUBCAMPANAPORCLIENTE FECHA_COACTIVA CARTERA
1000559797            1000559797  RECALDE ESPINOSA ALFONSO 5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  312
1000723724            1000723724  GARZON ECHEVERRIA JUAN   3.5 VENCIDA 0-30     NO COACTIVA    CORRIENTE   21
1000793024            1000793024  RODRIGUEZ MURIEL NOE     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  661
1001145398            1001145398  CIFUENTES REINA JOSE     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  652
1001213899            1001213899  DE JESUS BORJA OSCAR     5. VENCIDA FASE II   NO COACTIVA    CORRIENTE  515

In [38]:
asignacion_actual_men= asignacion_actual_men.fillna('')
asignacion_actual_men['ID']=asignacion_actual_men.apply(agregar_ceros,axis=1)
asignacion_actual_men['SUBCAMPANAPORCLIENTE'].replace(to_replace=[''],value='4. VENCIDA FASE I',inplace=True)
asignacion_actual_men['FECHA_COACTIVA'].replace(to_replace=[''],value='NO COACTIVA',inplace=True)
asignacion_actual_men['NOMBRE']=asignacion_actual_men['RAZONSOCIAL']+' '+asignacion_actual_men['PRIMER_APELLIDO']+' '+asignacion_actual_men['SEGUNDO_APELLIDO']+' '+asignacion_actual_men['PRIMER_NOMBRE']
asignacion_actual_men['CARTERA']='MENORES'
base_gestion_men=asignacion_actual_men[['IDENTIFICACION_DEUDOR','ID','NOMBRE','SALDO','FECHA_COACTIVA','CARTERA','SUBCAMPANAPORCLIENTE','DIAS_MORA']]
# ordenada_men=base_gestion_men.groupby(['IDENTIFICACION_DEUDOR','ID','NOMBRE','SUBCAMPANAPORCLIENTE','FECHA_COACTIVA']).sum()
ordenada_men=base_gestion_men.groupby(['IDENTIFICACION_DEUDOR','ID','NOMBRE','SUBCAMPANAPORCLIENTE','FECHA_COACTIVA','CARTERA']).agg({'SALDO':'sum','DIAS_MORA':['min', 'max']})

In [40]:
ordenada_men.head()

                                                                                                        SALDO  \
                                                                                                          sum
IDENTIFICACION_DEUDOR ID         NOMBRE                     SUBCAMPANAPORCLIENTE FECHA_COACTIVA CARTERA
00042448K             00042448K   ARAGON JUAREZ SERGIO      5. VENCIDA FASE II   NO COACTIVA    MENORES  57.9
1000005262            1000005262  NARVAEZ ANDRADE MARCELO   5. VENCIDA FASE II   43050.0        MENORES  19.3
1000026821            1000026821  LOPEZ GUERRA HUGO         3. MENORES           NO COACTIVA    MENORES  57.9
1000112654            1000112654  SISALEMA ALMEIDA CERVANDO 3. MENORES           NO COACTIVA    MENORES  36.6
1000131977            1000131977  SILVA  HECTOR             3. MENORES           NO COACTIVA    MENORES  54.9

                                                                                                        DIAS_MORA  \
                                                                                                              min
IDENTIFICACION_DEUDOR ID         NOMBRE                     SUBCAMPANAPORCLIENTE FECHA_COACTIVA CARTERA
00042448K             00042448K   ARAGON JUAREZ SERGIO      5. VENCIDA FASE II   NO COACTIVA    MENORES       167
1000005262            1000005262  NARVAEZ ANDRADE MARCELO   5. VENCIDA FASE II   43050.0        MENORES       103
1000026821            1000026821  LOPEZ GUERRA HUGO         3. MENORES           NO COACTIVA    MENORES        64
1000112654            1000112654  SISALEMA ALMEIDA CERVANDO 3. MENORES           NO COACTIVA    MENORES       910
1000131977            1000131977  SILVA  HECTOR             3. MENORES           NO COACTIVA    MENORES       857


                                                                                                         max
IDENTIFICACION_DEUDOR ID         NOMBRE                     SUBCAMPANAPORCLIENTE FECHA_COACTIVA CARTERA
00042448K             00042448K   ARAGON JUAREZ SERGIO      5. VENCIDA FASE II   NO COACTIVA    MENORES  167
1000005262            1000005262  NARVAEZ ANDRADE MARCELO   5. VENCIDA FASE II   43050.0        MENORES  103
1000026821            1000026821  LOPEZ GUERRA HUGO         3. MENORES           NO COACTIVA    MENORES   64
1000112654            1000112654  SISALEMA ALMEIDA CERVANDO 3. MENORES           NO COACTIVA    MENORES  910
1000131977            1000131977  SILVA  HECTOR             3. MENORES           NO COACTIVA    MENORES  857

In [44]:
base_total=pd.concat([ordenada_cor, ordenada_men])

In [48]:
writer = pd.ExcelWriter('..\..\CRUZAR NUMEROS\BASES CORRIENTE NEW.xlsx', engine='xlsxwriter')

base_total.to_excel(writer, sheet_name='BASE TOTAL')
worksheet = writer.sheets['BASE TOTAL']


# ordenada_cor.to_excel(writer, sheet_name='BASE CORRIENTE')
# worksheet = writer.sheets['BASE CORRIENTE']

# ordenada_men.to_excel(writer, sheet_name='BASE MENORES')
# worksheet = writer.sheets['BASE MENORES']

writer.save()